import { createClient } from "@boltic/sdk";
import {
  LeaderboardEntry,
  User,
  GameSession,
  Reward,
  CartAbandonment,
  Brand,
  CouponTemplate,
} from "../models/types";
import { IBolticService } from "./interfaces";

// Note: Tables use snake_case column names (user_id, game_name, etc.)
// Auto-generated columns: id, created_at, updated_at

export class BolticService implements IBolticService {
  private client: any;

  constructor() {
    // Lazy initialization - create client when service is instantiated
    const apiKey = process.env.BOLTIC_API_KEY;
    if (!apiKey) {
      throw new Error("BOLTIC_API_KEY environment variable is not set");
    }

    this.client = createClient(apiKey, {
      region: (process.env.BOLTIC_REGION as any) || "asia-south1",
      timeout: 30000,
      retryAttempts: 3,
      retryDelay: 1000,
      debug: process.env.NODE_ENV !== "production",
    });

    console.log(
      "[BolticService] Initialized with region:",
      process.env.BOLTIC_REGION || "asia-south1"
    );
  }

  /**
   * Insert a new leaderboard entry
   */
  async insertLeaderboardEntry(
    entry: Omit<LeaderboardEntry, "id">
  ): Promise<LeaderboardEntry> {
    const newEntry: LeaderboardEntry = {
      ...entry,
      id: this.generateId(),
    };

    try {
      // Using SQL INSERT for Boltic Tables (with snake_case column names)
      const sql = `
        INSERT INTO leaderboard ("mobile_number", "game_name", "score", "week_number", "timestamp")
        VALUES ('${newEntry.mobileNumber}', '${newEntry.gameName}', ${newEntry.score}, ${newEntry.weekNumber}, ${newEntry.timestamp});
      `;

      await this.executeSql(sql);
      console.log("[BolticService] Inserted leaderboard entry:", newEntry.id);
      return newEntry;
    } catch (error) {
      console.error(
        "[BolticService] Error inserting leaderboard entry:",
        error
      );
      throw error;
    }
  }

  /**
   * Get leaderboard for a specific game and week
   */
  async getLeaderboard(
    gameName: string,
    weekNumber: number,
    limit: number = 10
  ): Promise<LeaderboardEntry[]> {
    try {
      const sql = `
        SELECT l.*, u.username
        FROM leaderboard l
        LEFT JOIN users u ON u.mobile_number = l.mobile_number
        WHERE l."game_name" = '${this.escapeSql(gameName)}' 
          AND l."week_number" = ${weekNumber}
        ORDER BY l."score" DESC
        LIMIT ${limit};
      `;

      const rows = await this.executeSql(sql);
      console.log(
        "[BolticService] Retrieved leaderboard for",
        gameName,
        "week",
        weekNumber
      );

      return (rows || []).map((row: any) => ({
        id: row.id,
        mobileNumber: row.mobile_number,
        username: row.username,
        gameName: row.game_name,
        score: Number(row.score),
        weekNumber: Number(row.week_number),
        timestamp: Number(row.timestamp),
      }));
    } catch (error) {
      console.error("[BolticService] Error getting leaderboard:", error);
      return [];
    }
  }

  /**
   * Remove a leaderboard entry for a user and game
   */
  async removeLeaderboardEntry(
    mobileNumber: string,
    gameName: string
  ): Promise<boolean> {
    try {
      const sql = `
        DELETE FROM leaderboard 
        WHERE "mobile_number" = '${this.escapeSql(
          mobileNumber
        )}' AND "game_name" = '${this.escapeSql(gameName)}';
      `;

      await this.executeSql(sql);
      console.log(
        "[BolticService] Removed leaderboard entry for",
        mobileNumber,
        "in",
        gameName
      );
      return true;
    } catch (error) {
      console.error("[BolticService] Error removing leaderboard entry:", error);
      return false;
    }
  }

  /**
   * Generic insert method for any table
   */
  async insertRecord<T>(tableName: string, record: T): Promise<T> {
    try {
      // Convert camelCase keys to snake_case for database columns
      const camelToSnake = (str: string) =>
        str.replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`);

      // Helper to handle specific PK name or ID field differences if needed
      // e.g. sessionId -> session_id is handled by camelToSnake
      // rewardId -> reward_id is handled by camelToSnake

      // Auto-generated columns - exclude "id" if generated by DB, but we usually generate IDs in code.
      // Boltic auto-generates: id, created_at, updated_at if not provided?
      // Our schemas define explicit IDs usually.
      // The previous code had: const autoColumns = ["id", "created_at", "updated_at"];
      // But we often pass explicit `createdAt`.
      // Let's rely on the record passed in.

      const autoColumns = ["updated_at"]; // Exclude updated_at if managed by DB trigger? Or just include all.

      const entries = Object.entries(record as any).filter(
        ([key]) => !autoColumns.includes(camelToSnake(key))
      );

      const columns = entries
        .map(([col]) => `"${camelToSnake(col)}"`)
        .join(", ");

      const values = entries
        .map(([key, v]) => {
          const snakeKey = camelToSnake(key);
          // Numeric timestamp columns should stay as numbers
          if (
            [
              "timestamp",
              "expiry_date",
              "completed_at",
              "distributed_at",
            ].includes(snakeKey) &&
            typeof v === "number"
          ) {
            return v.toString();
          }
          return this.formatValue(v);
        })
        .join(", ");

      const sql = `
        INSERT INTO ${tableName} (${columns})
        VALUES (${values});
      `;

      await this.executeSql(sql);
      console.log("[BolticService] Inserted record into", tableName);
      return record;
    } catch (error) {
      console.error(
        "[BolticService] Error inserting record into",
        tableName,
        error
      );
      throw error;
    }
  }

  /**
   * Get user by Mobile Number
   */
  async getUser(mobileNumber: string): Promise<User | null> {
    try {
      const sql = `SELECT * FROM users WHERE "mobile_number" = '${this.escapeSql(
        mobileNumber
      )}' LIMIT 1;`;
      const rows = await this.executeSql(sql);
      const row = rows && rows.length > 0 ? rows[0] : null;

      if (!row) return null;

      // Map snake_case to camelCase User object
      return {
        mobileNumber: row.mobile_number,
        username: row.username,
        coinsBalance: Number(row.coins_balance || 0),
        dailyLoginStreak: Number(row.daily_login_streak || 0),
        lastLoginDate: row.last_login_date,
        totalGamesPlayed: Number(row.total_games_played || 0),
        totalWins: Number(row.total_wins || 0),
        winsThisWeek: Number(row.wins_this_week || 0),
        createdAt: Number(row.created_at),
        preferredStores: row.preferred_stores, // JSON if stored as such
      };
    } catch (error) {
      console.error("[BolticService] Error getting user:", error);
      return null;
    }
  }

  /**
   * Update user
   */
  async updateUser(
    mobileNumber: string,
    updates: Partial<User>
  ): Promise<User | null> {
    try {
      const camelToSnake = (str: string) =>
        str.replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`);

      const setClause = Object.entries(updates)
        .map(
          ([key, value]) =>
            `"${camelToSnake(key)}" = ${this.formatValue(value)}`
        )
        .join(", ");

      const sql = `UPDATE users SET ${setClause} WHERE "mobile_number" = '${this.escapeSql(
        mobileNumber
      )}';`;
      await this.executeSql(sql);

      return await this.getUser(mobileNumber);
    } catch (error) {
      console.error("[BolticService] Error updating user:", error);
      return null;
    }
  }

  /**
   * Check if username exists
   */
  async isUsernameExists(username: string): Promise<boolean> {
    try {
      const sql = `SELECT COUNT(*) as count FROM users WHERE LOWER("username") = LOWER('${this.escapeSql(
        username
      )}');`;
      const rows = await this.executeSql(sql);
      const count = rows && rows.length > 0 ? Number(rows[0].count) : 0;
      return count > 0;
    } catch (error) {
      console.error("[BolticService] Error checking username:", error);
      return false;
    }
  }

  /**
   * Get game sessions for a user
   */
  async getUserGameSessions(
    mobileNumber: string,
    limit: number = 10
  ): Promise<GameSession[]> {
    try {
      const sql = `
        SELECT * FROM game_sessions 
        WHERE "mobile_number" = '${this.escapeSql(mobileNumber)}' 
        ORDER BY "completed_at" DESC 
        LIMIT ${limit};
      `;
      const rows = await this.executeSql(sql);

      return (rows || []).map((row: any) => ({
        sessionId: row.session_id,
        mobileNumber: row.mobile_number,
        gameName: row.game_name,
        score: Number(row.score),
        coinsEarned: Number(row.coins_earned),
        rewardTier: row.reward_tier,
        completedAt: row.completed_at,
        isCartRecovery: row.is_cart_recovery,
        cartId: row.cart_id,
      }));
    } catch (error) {
      console.error("[BolticService] Error getting game sessions:", error);
      return [];
    }
  }

  /**
   * Get rewards for a user
   */
  async getUserRewards(
    mobileNumber: string,
    redeemedFilter?: boolean
  ): Promise<Reward[]> {
    try {
      let sql = `SELECT * FROM rewards WHERE "mobile_number" = '${this.escapeSql(
        mobileNumber
      )}'`;

      if (redeemedFilter !== undefined) {
        sql += ` AND "redeemed" = ${redeemedFilter}`;
      }

      sql += ` ORDER BY "distributed_at" DESC LIMIT 1000;`;

      const rows = await this.executeSql(sql);
      return (rows || []).map((row: any) => ({
        rewardId: row.reward_id,
        mobileNumber: row.mobile_number,
        rewardType: row.reward_type,
        rewardTier: row.reward_tier,
        discountPercentage: Number(row.discount_percentage),
        couponCode: row.coupon_code,
        expiryDate: Number(row.expiry_date),
        redeemed: !!row.redeemed,
        distributedAt: Number(row.distributed_at),
      }));
    } catch (error) {
      console.error("[BolticService] Error getting user rewards:", error);
      return [];
    }
  }

  /**
   * Insert a reward (coupon) for a user
   */
  async insertReward(reward: Reward): Promise<Reward> {
    try {
      const sql = `
        INSERT INTO rewards (
          "reward_id", "mobile_number", "reward_type", "reward_tier", 
          "discount_percentage", "coupon_code", "expiry_date", "redeemed", "distributed_at"
        )
        VALUES (
          '${reward.rewardId}',
          '${this.escapeSql(reward.mobileNumber)}',
          '${this.escapeSql(reward.rewardType)}',
          '${this.escapeSql(reward.rewardTier)}',
          ${reward.discountPercentage},
          '${this.escapeSql(reward.couponCode)}',
          ${reward.expiryDate},
          ${reward.redeemed ? "true" : "false"},
          ${reward.distributedAt}
        );
      `;
      await this.executeSql(sql);
      console.log("[BolticService] Inserted reward:", reward.rewardId);
      return reward;
    } catch (error) {
      console.error("[BolticService] Error inserting reward:", error);
      throw error;
    }
  }

  /**
   * Get cart abandonment by cart ID
   */
  async getCartAbandonment(cartId: string): Promise<CartAbandonment | null> {
    try {
      const sql = `SELECT * FROM cart_abandonments WHERE "cart_id" = '${this.escapeSql(
        cartId
      )}' LIMIT 1;`;
      const rows = await this.executeSql(sql);
      const row = rows && rows.length > 0 ? rows[0] : null;

      if (!row) return null;

      return {
        cartId: row.cart_id,
        mobileNumber: row.mobile_number,
        items: row.items, // JSON assumed handled by driver
        cartValue: Number(row.cart_value),
        createdAt: row.created_at,
        notificationSent: row.notification_sent,
        gameLink: row.game_link,
        converted: row.converted,
      };
    } catch (error) {
      console.error("[BolticService] Error getting cart abandonment:", error);
      return null;
    }
  }

  /**
   * Update cart abandonment
   */
  async updateCartAbandonment(
    cartId: string,
    updates: Partial<CartAbandonment>
  ): Promise<boolean> {
    try {
      const camelToSnake = (str: string) =>
        str.replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`);

      const setClause = Object.entries(updates)
        .map(
          ([key, value]) =>
            `"${camelToSnake(key)}" = ${this.formatValue(value)}`
        )
        .join(", ");

      const sql = `UPDATE cart_abandonments SET ${setClause} WHERE "cart_id" = '${this.escapeSql(
        cartId
      )}';`;
      await this.executeSql(sql);
      return true;
    } catch (error) {
      console.error("[BolticService] Error updating cart abandonment:", error);
      return false;
    }
  }

  /**
   * Send notification - Using Boltic Workflows/Streams if available
   * For now, this is a stub that would integrate with email service
   */
  async sendNotification(
    email: string,
    template: string,
    data: any
  ): Promise<{ status: string; messageId: string }> {
    console.log("[BolticService] Notification triggered:", {
      email,
      template,
      data,
    });

    // TODO: Integrate with Boltic Workflows for email sending
    // For hackathon, just log it
    return {
      status: "queued",
      messageId: `notification-${Date.now()}`,
    };
  }

  // ===== Helper Methods =====

  /**
   * Execute SQL query on Boltic Tables using the SDK
   */
  private async executeSql(sql: string): Promise<any> {
    try {
      console.log("[BolticService] Executing SQL:", sql);

      // Use the official SDK method: client.sql.executeSQL()
      const result = await this.client.sql.executeSQL(sql);

      // Check if there's an error in the response
      if (result.error) {
        const errorMsg = Array.isArray(result.error.meta)
          ? result.error.meta.join(", ")
          : result.error.meta || "Unknown error";

        // Provide helpful message for common errors
        if (errorMsg.includes("does not exist")) {
          throw new Error(
            `Table/Column not found: ${errorMsg}. Please create the required tables in Boltic Console.`
          );
        }
        throw new Error(`Boltic API Error: ${errorMsg}`);
      }

      // Response format for successful queries: { data: [], count: 0 }
      const rows = result.data || [];
      console.log(
        `[BolticService] Query executed successfully, returned ${
          Array.isArray(rows) ? rows.length : 0
        } rows`
      );
      return rows;
    } catch (error: any) {
      console.error(
        "[BolticService] SQL execution error:",
        error.message || error
      );
      throw error;
    }
  }

  /**
   * Format value for SQL based on type
   */
  private formatValue(value: any): string {
    if (value === null || value === undefined) {
      return "NULL";
    }
    if (typeof value === "string") {
      return `'${this.escapeSql(value)}'`;
    }
    if (typeof value === "boolean") {
      return value ? "true" : "false";
    }
    if (typeof value === "object") {
      // JSON fields
      return `'"${JSON.stringify(value).replace(/"/g, '\\"')}"'`;
    }
    return String(value);
  }

  /**
   * Escape SQL string to prevent injection
   */
  private escapeSql(str: string): string {
    if (!str) return "";
    return str.replace(/'/g, "''");
  }

  /**
   * Get User ID by Phone Number using "user_contact_mapping" table
   */
  async getUserIdByPhone(phoneNumber: string): Promise<string | null> {
    try {
      // Table name has spaces, so we quote it.
      // Using "mobile_number" as per new schema
      const sql = `SELECT "user_id" FROM "user_contact_mapping" WHERE "mobile_number" = '${this.escapeSql(
        phoneNumber
      )}' LIMIT 1;`;

      const result = await this.executeSql(sql);
      if (result && result.length > 0) {
        return result[0].user_id;
      }
      return null;
    } catch (error) {
      console.error("[BolticService] Error getting user ID by phone:", error);
      return null;
    }
  }

  /**
   * Create a mapping between Phone Number and User ID
   */
  async createMapping(phoneNumber: string, userId: string): Promise<boolean> {
    try {
      // Default app/company IDs if not provided (can be updated later)
      const appId = "6936cfcb5528738f3bdab871";
      const companyId = "12435";
      const now = Date.now();
      const id = this.generateId();

      const sql = `
        INSERT INTO "user_contact_mapping" (
          "id", "user_id", "mobile_number", "email", 
          "application_id", "company_id", "created_at", "updated_at"
        )
        VALUES (
          '${id}', 
          '${this.escapeSql(userId)}', 
          '${this.escapeSql(phoneNumber)}', 
          NULL, 
          '${appId}', 
          '${companyId}', 
          '${new Date(now).toISOString()}', 
          '${new Date(now).toISOString()}'
        );
      `;

      await this.executeSql(sql);
      console.log(
        `[BolticService] Created mapping for ${phoneNumber} -> ${userId}`
      );
      return true;
    } catch (error) {
      console.error("[BolticService] Error creating user mapping:", error);
      return false;
    }
  }

  // ===== Brand Management =====

  async getBrands(): Promise<Brand[]> {
    try {
      const sql = 'SELECT * FROM brands ORDER BY "created_at" DESC LIMIT 1000;';
      const rows = await this.executeSql(sql);
      // No mapping needed for simple Brand object if columns match or are simple
      // But let's be safe if ID/Name are standard.
      // Brand: id, name, createdAt. DB: id, name, created_at.
      return rows.map((row: any) => ({
        id: row.id,
        name: row.name,
        createdAt: row.created_at
          ? new Date(row.created_at).getTime()
          : Date.now(),
      }));
    } catch (error) {
      console.error("[BolticService] Error getting brands:", error);
      return [];
    }
  }

  async insertBrand(brand: Brand): Promise<Brand> {
    try {
      const sql = `
        INSERT INTO brands ("id", "name", "created_at")
        VALUES ('${brand.id}', '${this.escapeSql(brand.name)}', '${new Date(
        brand.createdAt
      ).toISOString()}');
      `;
      await this.executeSql(sql);
      return brand;
    } catch (error) {
      console.error("[BolticService] Error inserting brand:", error);
      throw error;
    }
  }

  async updateBrand(id: string, name: string): Promise<boolean> {
    try {
      const sql = `UPDATE brands SET "name" = '${this.escapeSql(
        name
      )}' WHERE "id" = '${this.escapeSql(id)}';`;
      await this.executeSql(sql);
      return true;
    } catch (error) {
      console.error("[BolticService] Error updating brand:", error);
      return false;
    }
  }

  async deleteBrand(id: string): Promise<boolean> {
    try {
      const sql = `DELETE FROM brands WHERE "id" = '${this.escapeSql(id)}';`;
      await this.executeSql(sql);
      return true;
    } catch (error) {
      console.error("[BolticService] Error deleting brand:", error);
      return false;
    }
  }

  async getCoupons(): Promise<CouponTemplate[]> {
    try {
      const sql =
        'SELECT * FROM coupon_templates ORDER BY "created_at" DESC LIMIT 1000;';
      const rows = await this.executeSql(sql);

      return rows.map((row: any) => ({
        id: row.id,
        brandId: row.brand_id,
        couponPrefix: row.coupon_prefix,
        discountPercentage: Number(row.discount_percentage),
        validityDays: Number(row.validity_days),
        rarityPercentage: Number(row.rarity_percentage),
        redeemUrl: row.redeem_url,
        terms: row.terms,
        createdAt: new Date(row.created_at).getTime(),
      }));
    } catch (error) {
      console.error("[BolticService] Error getting coupons:", error);
      return [];
    }
  }

  async insertCoupon(coupon: CouponTemplate): Promise<CouponTemplate> {
    try {
      const sql = `
        INSERT INTO coupon_templates (
          "id", "brand_id", "coupon_prefix", "discount_percentage", 
          "validity_days", "rarity_percentage", "redeem_url", "terms", "created_at"
        )
        VALUES (
          '${coupon.id}', 
          '${this.escapeSql(coupon.brandId)}', 
          '${this.escapeSql(coupon.couponPrefix)}', 
          ${coupon.discountPercentage}, 
          ${coupon.validityDays}, 
          ${coupon.rarityPercentage}, 
          '${this.escapeSql(coupon.redeemUrl)}', 
          '${this.escapeSql(coupon.terms)}', 
          '${new Date(coupon.createdAt).toISOString()}'
        );
      `;
      await this.executeSql(sql);
      return coupon;
    } catch (error) {
      console.error("[BolticService] Error inserting coupon:", error);
      throw error;
    }
  }

  async updateCoupon(
    id: string,
    updates: Partial<CouponTemplate>
  ): Promise<boolean> {
    try {
      const setParts = [];
      if (updates.brandId)
        setParts.push(`"brand_id" = '${this.escapeSql(updates.brandId)}'`);
      if (updates.couponPrefix)
        setParts.push(
          `"coupon_prefix" = '${this.escapeSql(updates.couponPrefix)}'`
        );
      if (updates.discountPercentage !== undefined)
        setParts.push(`"discount_percentage" = ${updates.discountPercentage}`);
      if (updates.validityDays !== undefined)
        setParts.push(`"validity_days" = ${updates.validityDays}`);
      if (updates.rarityPercentage !== undefined)
        setParts.push(`"rarity_percentage" = ${updates.rarityPercentage}`);
      if (updates.redeemUrl)
        setParts.push(`"redeem_url" = '${this.escapeSql(updates.redeemUrl)}'`);
      if (updates.terms)
        setParts.push(`"terms" = '${this.escapeSql(updates.terms)}'`);

      if (setParts.length === 0) return true;

      const sql = `UPDATE coupon_templates SET ${setParts.join(
        ", "
      )} WHERE "id" = '${this.escapeSql(id)}';`;
      await this.executeSql(sql);
      return true;
    } catch (error) {
      console.error("[BolticService] Error updating coupon:", error);
      return false;
    }
  }

  async deleteCoupon(id: string): Promise<boolean> {
    try {
      const sql = `DELETE FROM coupon_templates WHERE "id" = '${this.escapeSql(
        id
      )}';`;
      await this.executeSql(sql);
      return true;
    } catch (error) {
      console.error("[BolticService] Error deleting coupon:", error);
      return false;
    }
  }

  /**
   * Create a coupon via Boltic workflow
   * Calls the Make Coupon workflow endpoint with the Fynd coupon creation payload
   */
  async createCouponViaBoltic(
    couponCode: string,
    mobileNumber: string,
    couponPayload: any
  ): Promise<any> {
    try {
      const workflowUrl = process.env.BOLTIC_MAKE_COUPON_WORKFLOW_URL;
      if (!workflowUrl) {
        throw new Error(
          "BOLTIC_MAKE_COUPON_WORKFLOW_URL environment variable is not set"
        );
      }

      // Construct the URL with query parameters
      const url = new URL(workflowUrl);
      url.searchParams.set("coupon_code", couponCode);
      url.searchParams.set("mobile_number", mobileNumber);

      console.log(
        `[BolticService] Creating coupon via workflow for ${mobileNumber}, code: ${couponCode}`
      );

      // Make POST request with the coupon payload in the body
      const axios = require("axios");
      const response = await axios.post(url.toString(), couponPayload, {
        headers: {
          "Content-Type": "application/json",
        },
        timeout: 30000,
      });

      console.log(
        "[BolticService] Coupon creation workflow response:",
        response.data
      );
      return response.data;
    } catch (error: any) {
      console.error("[BolticService] Error creating coupon via Boltic:", error);
      throw error;
    }
  }

  /**
   * Generate unique ID
   */
  private generateId(): string {
    return require("crypto").randomUUID();
  }
}

// Lazy initialization - instance created on first access
let bolticInstance: BolticService | null = null;

export const boltic = new Proxy({} as BolticService, {
  get(target, prop) {
    if (!bolticInstance) {
      bolticInstance = new BolticService();
    }
    const value = (bolticInstance as any)[prop];
    return typeof value === "function" ? value.bind(bolticInstance) : value;
  },
});
